### PR TITLE
fix: no-extra-parens clashes with arrow-parens

### LINKED ISSUE #27: [Bug] no-extra-parens clashes with no-confusing arrow
**Describe the bug**

In a JavaScript file styling with styled-components this is a common pattern: 
```javascript
background: ${({ theme, primary }) => primary ? theme.color.butterscotch.tint : theme.color.hamam.tint};
```
But it warns because of the readability of the code. So I add two parentheses around the expression and it warns with another warning. 

**Context**

_It is best to provice which config (e.g. base or react) and rule is affected._
- Rule: _no-extra-parens clashes with no-confusing arrow_
- config: _base_

**To Reproduce**

1. fill in code
2. have both rules active

**Expected behavior**

I guess we should focus on readabiliy so the parens rule should be the one which we should keep turned on.

### PR DESCRIPTION
**Pull request by timidak**
closes #27

### CODE REVIEW

File: base.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ module.exports = {
     'array-func/prefer-flat': 'off', // https://github.com/freaktechnik/eslint-plugin-array-func#prefer-flat
     'array-func/prefer-flat-map': 'warn', // https://github.com/freaktechnik/eslint-plugin-array-func#prefer-flat-map
     'arrow-body-style': ['error', 'as-needed'], // https://eslint.org/docs/rules/arrow-body-style
-    'arrow-parens': ['error', 'as-needed'], // https://eslint.org/docs/rules/arrow-parens
+    'arrow-parens': ['error', 'always'], // https://eslint.org/docs/rules/arrow-parens
```
Comment (JoeTypeDigital) [inline base.js:51]: are you sure arror-parens: always doesn't cause other issues? i'm thinking about simple arrow functions here.
something like: array.map(x => x+1) should not require extra parens.
I don't know if that rule does that though. Could you verify that?

Comment (timidak) [reply base.js:51]: You are right in the map function it would require parens for the parameter `x`. I think that's ok and more consistent. Think about adding another parameter like `index` the second of the map function. Than we would have to add the parentheses anyways. 

Also when you think about destructuring in function parameters:
```javascript
myArray.map((data) => data.name)
myFunc(({}) => name)
```

As you can see having the parentheses seems more consistent to me so I would enforce them always. 

Have I convinced you?

Comment (JoeTypeDigital) [reply base.js:51]: yeah, i was just making sure that we thought about that case as well.
